//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Other/Input/InputActions/DebugInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DebugInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DebugInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DebugInput"",
    ""maps"": [
        {
            ""name"": ""Scene"",
            ""id"": ""d00efd91-1ab4-4534-8d4f-73761f9a78ee"",
            ""actions"": [
                {
                    ""name"": ""LoadPrevScene"",
                    ""type"": ""Button"",
                    ""id"": ""e2005bec-4b8f-4c19-8519-73b214029b44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadNextScene"",
                    ""type"": ""Button"",
                    ""id"": ""9533feab-3632-405e-9325-675632daf056"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadNowScene"",
                    ""type"": ""Button"",
                    ""id"": ""fa1757a2-d69a-4b19-b194-d343e967bbdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""key"",
                    ""id"": ""e4e84da9-6c4a-41d5-89f1-7fe2b91bee72"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""6c888204-5eef-4c04-ae30-0dd8693b0077"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4c31acf9-3f6c-4e92-aa76-4d75ea91b987"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""ae7e4a29-8e19-4865-9ea3-ec3d46011868"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a009b6af-1a80-40d7-8e8f-7eeb74289d29"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""f35d1ba6-05a5-4924-86de-f195784a4530"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadPrevScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""key"",
                    ""id"": ""00245dd6-c183-475b-a859-75c22458b0f9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""710133dc-018f-46d3-b60b-a01db86ff8f9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""00dcec61-b63c-4046-95d1-1348917fcbe0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""15429686-3bed-4861-8891-28c8ee3c0d71"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""55ba8e8e-7e4c-41a8-b64e-9005e14ceecf"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a6b01546-40c7-4667-ae85-8871cb8ceb7c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""key"",
                    ""id"": ""c8bf4af7-a26d-4e96-a2d2-8e0cba8cc382"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""025f1a2e-749b-4c72-b871-64423f493fce"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""20dc3934-5f3f-4930-924b-f7dd28310bb4"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""5b6c432b-fd71-4768-a107-4465d625fcfd"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9f5f61fd-5525-4850-bbbf-d16d4a50884b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7df17ade-d8f6-47ee-b549-e15131d4954f"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNowScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Time"",
            ""id"": ""94c5fe19-d58a-4bbe-8bbb-d161c5b8e486"",
            ""actions"": [
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""84f4c217-f2bb-4dbc-82c9-a5258f39299e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""bcb0a525-3b6d-45dd-a4f2-6cc2548f5e52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlowSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""3a3a7cf0-bde0-4647-a303-3b874ccf87d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""key"",
                    ""id"": ""26b1ee1e-3877-4a02-a25c-12e42011a0d1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""954b3d06-3b3c-4f60-866c-cf67fed509c4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ce0fe1cc-78ea-45e4-80c6-21261cb201aa"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""ce337d37-d1c4-48a8-a9a3-188e19eb204b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d9202596-0953-4677-855f-cf356bc966c7"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""837083ee-b887-47a9-8964-e5eeea32eaef"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""fbc3a9f1-05d2-4166-bfd5-46ab8d144e34"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""618db5b5-f36d-43bc-ae13-80a72b000f54"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""71fc4f7b-ebe5-4221-9fbf-adff1a6874d3"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ca5ba101-d628-48df-9a15-bea0e7a8bc72"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""key"",
                    ""id"": ""37672f08-3d7b-4ae4-9cff-33e904491d0f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1fc09afe-24e2-4cea-9f42-788d7f7d751d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e61e0600-0a4a-4a6d-9127-8665cc9b4c43"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""da4bc005-7a8a-418f-9ec3-2d27057288b6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""718de734-c41d-4bd0-b984-c8c65aee7193"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5f720286-9ae3-45d3-82f4-6808ea8eb7cf"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""key"",
                    ""id"": ""0dd89512-8c52-4ad3-9f7d-54808274e9f1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2cae2e0b-6522-421f-9805-96bb68902fc2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""743c7f14-6b96-46fb-a85d-609676423f78"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ctrl"",
                    ""id"": ""19c323c9-18fe-4a96-8d4b-aa4fcb0fbfcb"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""20401b44-99de-49eb-b148-127e502354cc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""eb6b7ad9-0597-4175-9653-79ab3afa981b"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""GameState"",
            ""id"": ""73e9cc0e-18e6-4678-9234-4be13e7b3941"",
            ""actions"": [
                {
                    ""name"": ""TransitionToEnd"",
                    ""type"": ""Button"",
                    ""id"": ""978539e2-8ac3-404e-87b3-53650a28040b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TransitionToResult"",
                    ""type"": ""Button"",
                    ""id"": ""74e2b17b-6286-43e1-bc9d-526f69af67a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipSetup"",
                    ""type"": ""Button"",
                    ""id"": ""b247d91c-39b5-43d5-b0b2-f28fc20e8f5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ce231eeb-e833-4819-b5bf-40421fdc5d13"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TransitionToEnd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a88d268-916e-4afa-b55e-6b8a207a8aa4"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TransitionToResult"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f76f948-5a5d-4fc3-88a0-42a00fa22de6"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipSetup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Scene
        m_Scene = asset.FindActionMap("Scene", throwIfNotFound: true);
        m_Scene_LoadPrevScene = m_Scene.FindAction("LoadPrevScene", throwIfNotFound: true);
        m_Scene_LoadNextScene = m_Scene.FindAction("LoadNextScene", throwIfNotFound: true);
        m_Scene_LoadNowScene = m_Scene.FindAction("LoadNowScene", throwIfNotFound: true);
        // Time
        m_Time = asset.FindActionMap("Time", throwIfNotFound: true);
        m_Time_Stop = m_Time.FindAction("Stop", throwIfNotFound: true);
        m_Time_FastSpeed = m_Time.FindAction("FastSpeed", throwIfNotFound: true);
        m_Time_SlowSpeed = m_Time.FindAction("SlowSpeed", throwIfNotFound: true);
        // GameState
        m_GameState = asset.FindActionMap("GameState", throwIfNotFound: true);
        m_GameState_TransitionToEnd = m_GameState.FindAction("TransitionToEnd", throwIfNotFound: true);
        m_GameState_TransitionToResult = m_GameState.FindAction("TransitionToResult", throwIfNotFound: true);
        m_GameState_SkipSetup = m_GameState.FindAction("SkipSetup", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Scene
    private readonly InputActionMap m_Scene;
    private ISceneActions m_SceneActionsCallbackInterface;
    private readonly InputAction m_Scene_LoadPrevScene;
    private readonly InputAction m_Scene_LoadNextScene;
    private readonly InputAction m_Scene_LoadNowScene;
    public struct SceneActions
    {
        private @DebugInput m_Wrapper;
        public SceneActions(@DebugInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @LoadPrevScene => m_Wrapper.m_Scene_LoadPrevScene;
        public InputAction @LoadNextScene => m_Wrapper.m_Scene_LoadNextScene;
        public InputAction @LoadNowScene => m_Wrapper.m_Scene_LoadNowScene;
        public InputActionMap Get() { return m_Wrapper.m_Scene; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SceneActions set) { return set.Get(); }
        public void SetCallbacks(ISceneActions instance)
        {
            if (m_Wrapper.m_SceneActionsCallbackInterface != null)
            {
                @LoadPrevScene.started -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadPrevScene;
                @LoadPrevScene.performed -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadPrevScene;
                @LoadPrevScene.canceled -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadPrevScene;
                @LoadNextScene.started -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNextScene;
                @LoadNextScene.performed -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNextScene;
                @LoadNextScene.canceled -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNextScene;
                @LoadNowScene.started -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNowScene;
                @LoadNowScene.performed -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNowScene;
                @LoadNowScene.canceled -= m_Wrapper.m_SceneActionsCallbackInterface.OnLoadNowScene;
            }
            m_Wrapper.m_SceneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LoadPrevScene.started += instance.OnLoadPrevScene;
                @LoadPrevScene.performed += instance.OnLoadPrevScene;
                @LoadPrevScene.canceled += instance.OnLoadPrevScene;
                @LoadNextScene.started += instance.OnLoadNextScene;
                @LoadNextScene.performed += instance.OnLoadNextScene;
                @LoadNextScene.canceled += instance.OnLoadNextScene;
                @LoadNowScene.started += instance.OnLoadNowScene;
                @LoadNowScene.performed += instance.OnLoadNowScene;
                @LoadNowScene.canceled += instance.OnLoadNowScene;
            }
        }
    }
    public SceneActions @Scene => new SceneActions(this);

    // Time
    private readonly InputActionMap m_Time;
    private ITimeActions m_TimeActionsCallbackInterface;
    private readonly InputAction m_Time_Stop;
    private readonly InputAction m_Time_FastSpeed;
    private readonly InputAction m_Time_SlowSpeed;
    public struct TimeActions
    {
        private @DebugInput m_Wrapper;
        public TimeActions(@DebugInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stop => m_Wrapper.m_Time_Stop;
        public InputAction @FastSpeed => m_Wrapper.m_Time_FastSpeed;
        public InputAction @SlowSpeed => m_Wrapper.m_Time_SlowSpeed;
        public InputActionMap Get() { return m_Wrapper.m_Time; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TimeActions set) { return set.Get(); }
        public void SetCallbacks(ITimeActions instance)
        {
            if (m_Wrapper.m_TimeActionsCallbackInterface != null)
            {
                @Stop.started -= m_Wrapper.m_TimeActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_TimeActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_TimeActionsCallbackInterface.OnStop;
                @FastSpeed.started -= m_Wrapper.m_TimeActionsCallbackInterface.OnFastSpeed;
                @FastSpeed.performed -= m_Wrapper.m_TimeActionsCallbackInterface.OnFastSpeed;
                @FastSpeed.canceled -= m_Wrapper.m_TimeActionsCallbackInterface.OnFastSpeed;
                @SlowSpeed.started -= m_Wrapper.m_TimeActionsCallbackInterface.OnSlowSpeed;
                @SlowSpeed.performed -= m_Wrapper.m_TimeActionsCallbackInterface.OnSlowSpeed;
                @SlowSpeed.canceled -= m_Wrapper.m_TimeActionsCallbackInterface.OnSlowSpeed;
            }
            m_Wrapper.m_TimeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @FastSpeed.started += instance.OnFastSpeed;
                @FastSpeed.performed += instance.OnFastSpeed;
                @FastSpeed.canceled += instance.OnFastSpeed;
                @SlowSpeed.started += instance.OnSlowSpeed;
                @SlowSpeed.performed += instance.OnSlowSpeed;
                @SlowSpeed.canceled += instance.OnSlowSpeed;
            }
        }
    }
    public TimeActions @Time => new TimeActions(this);

    // GameState
    private readonly InputActionMap m_GameState;
    private IGameStateActions m_GameStateActionsCallbackInterface;
    private readonly InputAction m_GameState_TransitionToEnd;
    private readonly InputAction m_GameState_TransitionToResult;
    private readonly InputAction m_GameState_SkipSetup;
    public struct GameStateActions
    {
        private @DebugInput m_Wrapper;
        public GameStateActions(@DebugInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @TransitionToEnd => m_Wrapper.m_GameState_TransitionToEnd;
        public InputAction @TransitionToResult => m_Wrapper.m_GameState_TransitionToResult;
        public InputAction @SkipSetup => m_Wrapper.m_GameState_SkipSetup;
        public InputActionMap Get() { return m_Wrapper.m_GameState; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameStateActions set) { return set.Get(); }
        public void SetCallbacks(IGameStateActions instance)
        {
            if (m_Wrapper.m_GameStateActionsCallbackInterface != null)
            {
                @TransitionToEnd.started -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToEnd;
                @TransitionToEnd.performed -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToEnd;
                @TransitionToEnd.canceled -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToEnd;
                @TransitionToResult.started -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToResult;
                @TransitionToResult.performed -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToResult;
                @TransitionToResult.canceled -= m_Wrapper.m_GameStateActionsCallbackInterface.OnTransitionToResult;
                @SkipSetup.started -= m_Wrapper.m_GameStateActionsCallbackInterface.OnSkipSetup;
                @SkipSetup.performed -= m_Wrapper.m_GameStateActionsCallbackInterface.OnSkipSetup;
                @SkipSetup.canceled -= m_Wrapper.m_GameStateActionsCallbackInterface.OnSkipSetup;
            }
            m_Wrapper.m_GameStateActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TransitionToEnd.started += instance.OnTransitionToEnd;
                @TransitionToEnd.performed += instance.OnTransitionToEnd;
                @TransitionToEnd.canceled += instance.OnTransitionToEnd;
                @TransitionToResult.started += instance.OnTransitionToResult;
                @TransitionToResult.performed += instance.OnTransitionToResult;
                @TransitionToResult.canceled += instance.OnTransitionToResult;
                @SkipSetup.started += instance.OnSkipSetup;
                @SkipSetup.performed += instance.OnSkipSetup;
                @SkipSetup.canceled += instance.OnSkipSetup;
            }
        }
    }
    public GameStateActions @GameState => new GameStateActions(this);
    public interface ISceneActions
    {
        void OnLoadPrevScene(InputAction.CallbackContext context);
        void OnLoadNextScene(InputAction.CallbackContext context);
        void OnLoadNowScene(InputAction.CallbackContext context);
    }
    public interface ITimeActions
    {
        void OnStop(InputAction.CallbackContext context);
        void OnFastSpeed(InputAction.CallbackContext context);
        void OnSlowSpeed(InputAction.CallbackContext context);
    }
    public interface IGameStateActions
    {
        void OnTransitionToEnd(InputAction.CallbackContext context);
        void OnTransitionToResult(InputAction.CallbackContext context);
        void OnSkipSetup(InputAction.CallbackContext context);
    }
}
